config/routes.rb
Rails.application.routes.draw do
  root 'bl_registry/registry_pages#index'

  namespace :bl_registry, path: '' do

    resource :react, controller: 'registry_react', only: [] do
      collection do
        get :client
        get :server
      end
    end

  end

  namespace :bl_admin do
    get '' => 'admin_pages#index'

    resource :react, controller: 'admin_react', only: [] do
      collection do
        get :client
      end
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bl_admin/admin_pages_controller.rb
module BLAdmin
  class AdminPagesController < BLAdmin::ApplicationController

    def index
    end

  end
end

app/controllers/bl_admin/admin_react_controller.rb
module BLAdmin
  class AdminReactController < BLAdmin::ApplicationController

    def client
    end

  end
end

app/controllers/bl_admin/application_controller.rb
module BLAdmin
  class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception
    layout 'bl_admin/layouts/application'
  end
end

app/controllers/bl_registry/registry_pages_controller.rb
module BLRegistry
  class RegistryPagesController < ApplicationController

    def index
    end

  end
end

app/controllers/bl_registry/registry_react_controller.rb
module BLRegistry
  class RegistryReactController < ApplicationController

    def client
    end

    def server
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def find_asset(logical_path)
    if Rails.application.config.assets.compile
      assets.find_asset(logical_path)
    else
      assets_manifest.assets[logical_path]
    end
  end

end

app/views/bl_admin/admin_pages/index.html.erb
ADMIN No React Index Page

app/views/bl_admin/admin_react/client.html.erb
<%= react_component('AdminClientRendered') %>

app/views/bl_admin/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ADMIN Boilerplate</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "#{params[:controller]}/#{params[:action]}" if Rails.application.assets.find_asset("#{params[:controller]}/#{params[:action]}.js") %>

    <% if ENV['REACT_ON_RAILS_ENV'] == 'HOT' %>
      <%= javascript_include_tag 'http://localhost:3500/vendor-bundle.js' %>
      <%= javascript_include_tag 'http://localhost:3500/admin-bundle.js' %>
    <% else %>
      <%= javascript_include_tag 'webpack/vendor-bundle.js' %>
      <%= javascript_include_tag 'webpack/admin-bundle.js' %>
    <% end %>

    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render partial: 'shared/nav' %>
    <%= yield %>
  </body>
</html>

app/views/bl_registry/registry_pages/index.html.erb
No React Index Page

app/views/bl_registry/registry_react/client.html.erb
<%= react_component('ClientRendered') %>

app/views/bl_registry/registry_react/server.html.erb
<%= react_component('ServerRendered', {}, { prerender: true }) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Boilerplate</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "#{params[:controller]}/#{params[:action]}" if Rails.application.assets.find_asset("#{params[:controller]}/#{params[:action]}.js") %>

    <% if ENV['REACT_ON_RAILS_ENV'] == 'HOT' %>
      <%= javascript_include_tag 'http://localhost:3500/vendor-bundle.js' %>
      <%= javascript_include_tag 'http://localhost:3500/app-bundle.js' %>
    <% else %>
      <%= javascript_include_tag 'webpack/vendor-bundle.js' %>
      <%= javascript_include_tag 'webpack/app-bundle.js' %>
    <% end %>

    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render partial: 'shared/nav' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_nav.html.erb
<ul>
  <li><%= link_to 'Static Page', root_path %></li>
  <li><%= link_to 'Client Rendered React', client_bl_registry_react_path %></li>
  <li><%= link_to 'Server Rendered React', server_bl_registry_react_path %></li>
  <li><%= link_to 'Admin Static Page', bl_admin_path %></li>
  <li><%= link_to 'Admin Client Rendered React', client_bl_admin_react_path %></li>
</ul>